FROM microsoft/dotnet:2.1-sdk AS build
COPY ./app ./app
WORKDIR /app/
RUN dotnet build -c Release -o output

FROM microsoft/dotnet:2.1-runtime AS runtime
COPY --from=build /app/output .
ENTRYPOINT ["dotnet", "app.dll"]
