version: '3'

services:
  web:
    image: branor/compose
    build: .
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
  redis:
    image: redis:alpine
