apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  labels:
    run: nodeapp
spec:
  ports:
  - port: 6060
    targetPort: 6060
    nodePort: 30060
    protocol: TCP
  selector:
    app: nodeapp
  type: LoadBalancer

