version: '3'

services:

  metrics:
    image: branor/metrics:latest
    build:
      context: .
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "5050:5050"

networks:
  default:
    external:
      name: ndcswarm
